// GENERATED by tool/gen_text.py. Do not edit.
import 'package:flutter/widgets.dart';
import 'package:flutter_motion_kit/flutter_motion_kit.dart';

enum TextKind { enter, loop, hover }

enum TextSplit { char, word, text }

final textWidgets =
    <String, (TextKind, TextSplit, Widget Function(String text))>{
      'DiaTextReveal': (
        TextKind.enter,
        TextSplit.text,
        (s) => DiaTextReveal(s),
      ),
      'BlurText': (TextKind.enter, TextSplit.text, (s) => BlurText(s)),
      'ShimmerText': (TextKind.loop, TextSplit.text, (s) => ShimmerText(s)),
      'TypewriterText': (
        TextKind.enter,
        TextSplit.text,
        (s) => TypewriterText(s),
      ),
      'RevealText': (TextKind.enter, TextSplit.text, (s) => RevealText(s)),
      'FadeInChar': (TextKind.enter, TextSplit.char, (s) => FadeInChar(s)),
      'FadeInWord': (TextKind.enter, TextSplit.word, (s) => FadeInWord(s)),
      'FadeInText': (TextKind.enter, TextSplit.text, (s) => FadeInText(s)),
      'BlurUpWord': (TextKind.enter, TextSplit.word, (s) => BlurUpWord(s)),
      'BlurUpChar': (TextKind.enter, TextSplit.char, (s) => BlurUpChar(s)),
      'StaggerText': (TextKind.enter, TextSplit.word, (s) => StaggerText(s)),
      'SlideUpChar': (TextKind.enter, TextSplit.char, (s) => SlideUpChar(s)),
      'SlideUpWord': (TextKind.enter, TextSplit.word, (s) => SlideUpWord(s)),
      'SlideUpText': (TextKind.enter, TextSplit.text, (s) => SlideUpText(s)),
      'SlideDownChar': (
        TextKind.enter,
        TextSplit.char,
        (s) => SlideDownChar(s),
      ),
      'SlideDownWord': (
        TextKind.enter,
        TextSplit.word,
        (s) => SlideDownWord(s),
      ),
      'SlideLeftChar': (
        TextKind.enter,
        TextSplit.char,
        (s) => SlideLeftChar(s),
      ),
      'SlideRightChar': (
        TextKind.enter,
        TextSplit.char,
        (s) => SlideRightChar(s),
      ),
      'DropInChar': (TextKind.enter, TextSplit.char, (s) => DropInChar(s)),
      'RiseUpWord': (TextKind.enter, TextSplit.word, (s) => RiseUpWord(s)),
      'BounceInChar': (TextKind.enter, TextSplit.char, (s) => BounceInChar(s)),
      'ScaleInChar': (TextKind.enter, TextSplit.char, (s) => ScaleInChar(s)),
      'ScaleInWord': (TextKind.enter, TextSplit.word, (s) => ScaleInWord(s)),
      'ScaleInText': (TextKind.enter, TextSplit.text, (s) => ScaleInText(s)),
      'ZoomInText': (TextKind.enter, TextSplit.text, (s) => ZoomInText(s)),
      'ZoomOutText': (TextKind.enter, TextSplit.text, (s) => ZoomOutText(s)),
      'FlipYChar': (TextKind.enter, TextSplit.char, (s) => FlipYChar(s)),
      'FlipXChar': (TextKind.enter, TextSplit.char, (s) => FlipXChar(s)),
      'RotateInChar': (TextKind.enter, TextSplit.char, (s) => RotateInChar(s)),
      'SwingWord': (TextKind.enter, TextSplit.word, (s) => SwingWord(s)),
      'StretchXChar': (TextKind.enter, TextSplit.char, (s) => StretchXChar(s)),
      'StretchYChar': (TextKind.enter, TextSplit.char, (s) => StretchYChar(s)),
      'SkewXChar': (TextKind.enter, TextSplit.char, (s) => SkewXChar(s)),
      'TrackingInText': (
        TextKind.enter,
        TextSplit.text,
        (s) => TrackingInText(s),
      ),
      'TrackingOutText': (
        TextKind.enter,
        TextSplit.text,
        (s) => TrackingOutText(s),
      ),
      'SpringText': (TextKind.hover, TextSplit.char, (s) => SpringText(s)),
      'HoverLiftChar': (
        TextKind.hover,
        TextSplit.char,
        (s) => HoverLiftChar(s),
      ),
      'HoverLiftWord': (
        TextKind.hover,
        TextSplit.word,
        (s) => HoverLiftWord(s),
      ),
      'HoverScaleChar': (
        TextKind.hover,
        TextSplit.char,
        (s) => HoverScaleChar(s),
      ),
      'HoverScaleWord': (
        TextKind.hover,
        TextSplit.word,
        (s) => HoverScaleWord(s),
      ),
      'FloatChar': (TextKind.loop, TextSplit.char, (s) => FloatChar(s)),
      'FloatWord': (TextKind.loop, TextSplit.word, (s) => FloatWord(s)),
      'PulseChar': (TextKind.loop, TextSplit.char, (s) => PulseChar(s)),
      'PulseWord': (TextKind.loop, TextSplit.word, (s) => PulseWord(s)),
      'GlowText': (TextKind.loop, TextSplit.text, (s) => GlowText(s)),
    };
