// GENERATED by tool/gen_toggles.py. Do not edit.
import 'package:flutter/widgets.dart';
import 'package:flutter_motion_kit/flutter_motion_kit.dart';

/// Every on/off toggle, built controlled (value + onChanged) or uncontrolled (value null).
final toggleWidgets = <String, Widget Function(bool? value, ValueChanged<bool>? onChanged)>{
  'DoubleBounceSwitch': (v, f) => DoubleBounceSwitch(value: v, onChanged: f),
  'SolidSwitch': (v, f) => SolidSwitch(value: v, onChanged: f),
  'RectangleSwitch': (v, f) => RectangleSwitch(value: v, onChanged: f),
  'CircleSwitch': (v, f) => CircleSwitch(value: v, onChanged: f),
  'ClassicSwitch': (v, f) => ClassicSwitch(value: v, onChanged: f),
  'MorphSwitch': (v, f) => MorphSwitch(value: v, onChanged: f),
  'CheckmarkSwitch': (v, f) => CheckmarkSwitch(value: v, onChanged: f),
  'ThemeSwitch': (v, f) => ThemeSwitch(value: v, onChanged: f),
  'BookmarkToggle': (v, f) => BookmarkToggle(value: v, onChanged: f),
  'LikeToggle': (v, f) => LikeToggle(value: v, onChanged: f),
  'DislikeToggle': (v, f) => DislikeToggle(value: v, onChanged: f),
  'RepostToggle': (v, f) => RepostToggle(value: v, onChanged: f),
};
