// GENERATED by tool/gen_cards.py. Do not edit.
import 'package:flutter/widgets.dart';
import 'package:flutter_motion_kit/flutter_motion_kit.dart';

typedef CardEntry = ({String name, String source, Widget Function(bool hovered) builder});

final List<CardEntry> hoverCardCatalog = [
  (name: 'Arc 5', source: 'cards/card_arc.dart', builder: (hovered) => CardArc(hovered: hovered)),
  (name: 'Arc 7', source: 'cards/card_arc.dart', builder: (hovered) => CardArc.seven(hovered: hovered)),
  (name: 'Long Arc 5', source: 'cards/card_arc.dart', builder: (hovered) => CardArc.long(hovered: hovered)),
  (
    name: 'Linear Spread',
    source: 'cards/card_linear_spread.dart',
    builder: (hovered) => CardLinearSpread(hovered: hovered),
  ),
  (
    name: 'Corner Fan',
    source: 'cards/card_corner_fan.dart',
    builder: (hovered) => CardCornerFan(hovered: hovered),
  ),
  (
    name: 'Stamp Arc',
    source: 'cards/card_stamp_arc.dart',
    builder: (hovered) => CardStampArc(hovered: hovered),
  ),
  (
    name: 'Stamp Arc · Colorful',
    source: 'cards/card_stamp_arc.dart',
    builder: (hovered) => CardStampArc(colorful: true, hovered: hovered),
  ),
  (
    name: 'Cascade Stagger',
    source: 'cards/card_cascade_stagger.dart',
    builder: (hovered) => CardCascadeStagger(hovered: hovered),
  ),
  (
    name: 'Scatter Spread',
    source: 'cards/card_scatter_spread.dart',
    builder: (hovered) => CardScatterSpread(hovered: hovered),
  ),
  (
    name: 'Wheel Fan',
    source: 'cards/card_wheel_fan.dart',
    builder: (hovered) => CardWheelFan(hovered: hovered),
  ),
];
