// GENERATED by tool/gen_loaders.py. Do not edit.
import 'package:flutter/widgets.dart';
import 'package:flutter_motion_kit/flutter_motion_kit.dart';

typedef LoaderEntry = ({String name, String category, String source, WidgetBuilder builder});

final List<LoaderEntry> loaderCatalog = [
  (
    name: 'Pulse Dots',
    category: 'Dots',
    source: 'loaders/pulse_dots.dart',
    builder: (_) => const PulseDots(),
  ),
  (
    name: 'Bounce Dots',
    category: 'Dots',
    source: 'loaders/bounce_dots.dart',
    builder: (_) => const BounceDots(),
  ),
  (name: 'Wave Dots', category: 'Dots', source: 'loaders/wave_dots.dart', builder: (_) => const WaveDots()),
  (name: 'Grid Dots', category: 'Dots', source: 'loaders/grid_dots.dart', builder: (_) => const GridDots()),
  (
    name: 'Typing Indicator',
    category: 'Dots',
    source: 'loaders/typing_indicator.dart',
    builder: (_) => const TypingIndicator(),
  ),
  (name: 'Dots Ring', category: 'Dots', source: 'loaders/dots_ring.dart', builder: (_) => const DotsRing()),
  (
    name: 'Classic Spinner',
    category: 'Rings',
    source: 'loaders/classic_spinner.dart',
    builder: (_) => const ClassicSpinner(),
  ),
  (
    name: 'iOS Spinner',
    category: 'Rings',
    source: 'loaders/ios_spinner.dart',
    builder: (_) => const IOSSpinner(),
  ),
  (
    name: 'Comet Spinner',
    category: 'Rings',
    source: 'loaders/comet_spinner.dart',
    builder: (_) => const CometSpinner(),
  ),
  (
    name: 'Arc Tracer',
    category: 'Rings',
    source: 'loaders/arc_tracer.dart',
    builder: (_) => const ArcTracer(),
  ),
  (name: 'Dual Arc', category: 'Rings', source: 'loaders/dual_arc.dart', builder: (_) => const DualArc()),
  (
    name: 'Orbiting Dot',
    category: 'Rings',
    source: 'loaders/orbiting_dot.dart',
    builder: (_) => const OrbitingDot(),
  ),
  (
    name: 'Ripple Effect',
    category: 'Rings',
    source: 'loaders/ripple_effect.dart',
    builder: (_) => const RippleEffect(),
  ),
  (
    name: 'Bouncing Bars',
    category: 'Bars',
    source: 'loaders/bouncing_bars.dart',
    builder: (_) => const BouncingBars(),
  ),
  (
    name: 'Bar Cascade',
    category: 'Bars',
    source: 'loaders/bar_cascade.dart',
    builder: (_) => const BarCascade(),
  ),
  (name: 'Equalizer', category: 'Bars', source: 'loaders/equalizer.dart', builder: (_) => const Equalizer()),
  (
    name: 'Flip Square',
    category: 'Shapes',
    source: 'loaders/flip_square.dart',
    builder: (_) => const FlipSquare(),
  ),
  (
    name: "Newton's Cradle",
    category: 'Shapes',
    source: 'loaders/newtons_cradle.dart',
    builder: (_) => const NewtonsCradle(),
  ),
  (
    name: 'Square Spinner',
    category: 'Shapes',
    source: 'loaders/square_spinner.dart',
    builder: (_) => const SquareSpinner(),
  ),
  (
    name: 'Text Shimmer',
    category: 'Text',
    source: 'loaders/text_shimmer.dart',
    builder: (_) => const TextShimmer(),
  ),
];
