// GENERATED by tool/gen_mono_charts.py. Do not edit.
import 'package:flutter/material.dart';
import 'package:flutter_motion_kit/flutter_motion_kit.dart';

typedef MonoChartEntry = ({String name, String source, WidgetBuilder builder});
final List<MonoChartEntry> monoChartCatalog = [
  (
    name: 'Emerald Activity Heatmap',
    source: 'charts/mono_activity_heatmap.dart',
    builder: (_) => const MonoActivityHeatmap(width: 420, height: 260),
  ),
  (
    name: 'Sky Blue Activity Heatmap',
    source: 'charts/mono_activity_heatmap.dart',
    builder: (_) => const MonoActivityHeatmap(width: 420, height: 260, color: Color(0xFF38BDF8)),
  ),
  (
    name: 'Violet Activity Heatmap',
    source: 'charts/mono_activity_heatmap.dart',
    builder: (_) => const MonoActivityHeatmap(width: 420, height: 260, color: Color(0xFFC084FC)),
  ),
  (
    name: 'Rounded Spline Line',
    source: 'charts/mono_rounded_line_chart.dart',
    builder: (_) => const MonoRoundedLineChart(width: 420, height: 260),
  ),
  (
    name: 'Rounded Pill Pillars',
    source: 'charts/mono_rounded_bar_chart.dart',
    builder: (_) => const MonoRoundedBarChart(width: 420, height: 260),
  ),
  (
    name: 'Curved Wave Area',
    source: 'charts/mono_rounded_area_chart.dart',
    builder: (_) => const MonoRoundedAreaChart(width: 420, height: 260),
  ),
  (
    name: 'Rounded Donut Ring',
    source: 'charts/mono_rounded_donut_chart.dart',
    builder: (_) => const MonoRoundedDonutChart(width: 420, height: 260),
  ),
  (
    name: 'Hybrid Spline + Bar',
    source: 'charts/mono_rounded_composed_chart.dart',
    builder: (_) => const MonoRoundedComposedChart(width: 420, height: 260),
  ),
  (
    name: 'Scatter Matrix',
    source: 'charts/mono_rounded_scatter_chart.dart',
    builder: (_) => const MonoRoundedScatterChart(width: 420, height: 260),
  ),
  (
    name: 'Financial Candlesticks',
    source: 'charts/mono_rounded_candlestick_chart.dart',
    builder: (_) => const MonoRoundedCandlestickChart(width: 420, height: 260),
  ),
  (
    name: 'Stat KPI Card',
    source: 'charts/mono_rounded_kpi_card_chart.dart',
    builder: (_) => const MonoRoundedKpiCardChart(width: 420, height: 260),
  ),
  (
    name: 'Tier Pyramid Stack',
    source: 'charts/mono_rounded_pyramid_chart.dart',
    builder: (_) => const MonoRoundedPyramidChart(width: 420, height: 260),
  ),
  (
    name: 'Radial Bar Group',
    source: 'charts/mono_rounded_radial_bar_group.dart',
    builder: (_) => const MonoRoundedRadialBarGroup(width: 420, height: 260),
  ),
  (
    name: 'Speedometer Gauge Arc',
    source: 'charts/mono_rounded_gauge_arc.dart',
    builder: (_) => const MonoRoundedGaugeArc(width: 420, height: 260),
  ),
  (
    name: 'Performance Bullet Target',
    source: 'charts/mono_rounded_bullet_chart.dart',
    builder: (_) => const MonoRoundedBulletChart(width: 420, height: 260),
  ),
  (
    name: 'Flow Sankey Channels',
    source: 'charts/mono_rounded_sankey_chart.dart',
    builder: (_) => const MonoRoundedSankeyChart(width: 420, height: 260),
  ),
  (
    name: 'Step Progression',
    source: 'charts/mono_rounded_step_chart.dart',
    builder: (_) => const MonoRoundedStepChart(width: 420, height: 260),
  ),
  (
    name: 'Stacked Tones Bar',
    source: 'charts/mono_rounded_stacked_bar_chart.dart',
    builder: (_) => const MonoRoundedStackedBarChart(width: 420, height: 260),
  ),
  (
    name: 'Polygon Web Radar',
    source: 'charts/mono_rounded_radar_chart.dart',
    builder: (_) => const MonoRoundedRadarChart(width: 420, height: 260),
  ),
  (
    name: 'Concentric Radial Rings',
    source: 'charts/mono_rounded_radial_gauge_chart.dart',
    builder: (_) => const MonoRoundedRadialGaugeChart(width: 420, height: 260),
  ),
  (
    name: 'Stage Funnel',
    source: 'charts/mono_rounded_funnel_chart.dart',
    builder: (_) => const MonoRoundedFunnelChart(width: 420, height: 260),
  ),
  (
    name: 'Dot Matrix Heatmap',
    source: 'charts/mono_rounded_heatmap_chart.dart',
    builder: (_) => const MonoRoundedHeatmapChart(width: 420, height: 260),
  ),
  (
    name: 'Sparkline Telemetry',
    source: 'charts/mono_rounded_sparkline_chart.dart',
    builder: (_) => const MonoRoundedSparklineChart(width: 420, height: 260),
  ),
  (
    name: 'Bubble Clusters',
    source: 'charts/mono_rounded_bubble_chart.dart',
    builder: (_) => const MonoRoundedBubbleChart(width: 420, height: 260),
  ),
  (
    name: 'Tile Treemap',
    source: 'charts/mono_rounded_treemap_chart.dart',
    builder: (_) => const MonoRoundedTreemapChart(width: 420, height: 260),
  ),
  (
    name: 'Fluid Stream Wave',
    source: 'charts/mono_rounded_stream_chart.dart',
    builder: (_) => const MonoRoundedStreamChart(width: 420, height: 260),
  ),
  (
    name: 'Arc Meter Gauge',
    source: 'charts/mono_rounded_meter_chart.dart',
    builder: (_) => const MonoRoundedMeterChart(width: 420, height: 260),
  ),
  (
    name: 'Waterfall Steps',
    source: 'charts/mono_rounded_waterfall_chart.dart',
    builder: (_) => const MonoRoundedWaterfallChart(width: 420, height: 260),
  ),
  (
    name: 'Polar Radial Pillars',
    source: 'charts/mono_rounded_polar_chart.dart',
    builder: (_) => const MonoRoundedPolarChart(width: 420, height: 260),
  ),
  (
    name: 'Range Band Area',
    source: 'charts/mono_rounded_range_chart.dart',
    builder: (_) => const MonoRoundedRangeChart(width: 420, height: 260),
  ),
];
