// GENERATED by tool/gen_toggles.py. Do not edit.
import 'package:flutter/widgets.dart';
import 'package:flutter_motion_kit/flutter_motion_kit.dart';

typedef ToggleEntry = ({String name, String source, WidgetBuilder builder});

final List<ToggleEntry> toggleCatalog = [
  (
    name: 'Double Bounce Switch',
    source: 'toggles/double_bounce_switch.dart',
    builder: (_) => const DoubleBounceSwitch(),
  ),
  (name: 'Solid Switch', source: 'toggles/solid_switch.dart', builder: (_) => const SolidSwitch()),
  (name: 'Rectangle Toggle', source: 'toggles/rectangle_switch.dart', builder: (_) => const RectangleSwitch()),
  (name: 'Circle Curve Toggle', source: 'toggles/circle_switch.dart', builder: (_) => const CircleSwitch()),
  (name: 'Bookmark Action', source: 'toggles/bookmark_toggle.dart', builder: (_) => const BookmarkToggle()),
  (name: 'Like Action', source: 'toggles/like_toggle.dart', builder: (_) => const LikeToggle(count: 42)),
  (name: 'Dislike Action', source: 'toggles/dislike_toggle.dart', builder: (_) => const DislikeToggle()),
  (name: 'Repost Action', source: 'toggles/repost_toggle.dart', builder: (_) => const RepostToggle(count: 18)),
  (name: 'Pill Tabs Switcher', source: 'toggles/pill_tabs.dart', builder: (_) => const PillTabs()),
  (name: 'Morph Toggle', source: 'toggles/morph_switch.dart', builder: (_) => const MorphSwitch()),
  (name: 'Checkmark Draw', source: 'toggles/checkmark_switch.dart', builder: (_) => const CheckmarkSwitch()),
  (name: 'Theme Toggle', source: 'toggles/theme_switch.dart', builder: (_) => const ThemeSwitch()),
  (name: 'Classic Toggle', source: 'toggles/classic_switch.dart', builder: (_) => const ClassicSwitch()),
];
