// GENERATED by tool/gen_mono_charts.py. Edit the generator, then regenerate.
// MonoRoundedMeterChart — Arc Meter Gauge.
// Inspired by Amicro (MIT, (c) 2026 Syed Subhan Uddin).
// Copy this file into your project. It depends only on Flutter and dart:math.
// Usage: MonoRoundedMeterChart() or MonoRoundedMeterChart(data: [MonoRoundedMeterPoint(label: 'A', value: 42)])
import 'dart:math' as math;

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

/// One observation. Values use the units supplied to the chart.
@immutable
class MonoRoundedMeterPoint {
  const MonoRoundedMeterPoint({required this.label, required this.value});
  final String label;
  final double value;
}

/// A standalone, rounded chart with hover/tap inspection and an animated reveal.
/// Defaults are demonstration data; provide [data] or named [datasets] for your own.
/// Theme colours follow the surrounding Material theme. Reduced motion is respected.
class MonoRoundedMeterChart extends StatefulWidget {
  const MonoRoundedMeterChart({
    super.key,
    this.data,
    this.datasets,
    this.width = 420,
    this.height = 260,
    this.color,
    this.backgroundColor,
    this.unit = '% efficiency',
    this.animate = true,
    this.duration = const Duration(milliseconds: 650),
    this.onSelected,
  }) : assert(width > 0),
       assert(height >= 140);

  /// A single series. Overrides the demonstration datasets when provided.
  final List<MonoRoundedMeterPoint>? data;

  /// Named series shown in a selector. Takes precedence over [data].
  final Map<String, List<MonoRoundedMeterPoint>>? datasets;
  final double width;
  final double height;
  final Color? color;
  final Color? backgroundColor;
  final String unit;
  final bool animate;
  final Duration duration;

  /// Reports the hovered/tapped observation; null when the selection is cleared.
  final ValueChanged<MonoRoundedMeterPoint?>? onSelected;

  @override
  State<MonoRoundedMeterChart> createState() => _ChartState();
}

const _demo = <String, List<MonoRoundedMeterPoint>>{
  'Default': [MonoRoundedMeterPoint(label: 'Efficiency', value: 88)],
};

class _ChartState extends State<MonoRoundedMeterChart> with SingleTickerProviderStateMixin {
  late final AnimationController _animation = AnimationController(vsync: this, duration: widget.duration);
  String? _dataset;
  int? _selected;
  bool? _reducedMotion;

  Map<String, List<MonoRoundedMeterPoint>> get _sets =>
      widget.datasets ?? (widget.data == null ? _demo : const {});
  String? get _active => _sets.containsKey(_dataset) ? _dataset : (_sets.isEmpty ? null : _sets.keys.first);
  List<MonoRoundedMeterPoint> get _data => List.unmodifiable(
    (_active == null ? widget.data ?? const <MonoRoundedMeterPoint>[] : _sets[_active]!).where(
      (d) => d.value.isFinite,
    ),
  );

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final reduced = MediaQuery.disableAnimationsOf(context);
    if (_reducedMotion != reduced) {
      _reducedMotion = reduced;
      _reveal();
    }
  }

  @override
  void didUpdateWidget(covariant MonoRoundedMeterChart oldWidget) {
    super.didUpdateWidget(oldWidget);
    _animation.duration = widget.duration;
    if (oldWidget.data != widget.data ||
        oldWidget.datasets != widget.datasets ||
        oldWidget.animate != widget.animate) {
      _selected = null;
      _reveal();
    }
  }

  void _reveal() {
    if (_reducedMotion == true || !widget.animate) {
      _animation.value = 1;
    } else {
      _animation.forward(from: 0);
    }
  }

  void _select(int? index, List<MonoRoundedMeterPoint> data) {
    if (_selected == index) return;
    setState(() => _selected = index);
    widget.onSelected?.call(index == null ? null : data[index]);
  }

  @override
  void dispose() {
    _animation.dispose();
    super.dispose();
  }

  String _detail(MonoRoundedMeterPoint d) => '${d.label}: ${_number(d.value)} ${widget.unit}';

  @override
  Widget build(BuildContext context) {
    final dark = Theme.of(context).brightness == Brightness.dark;
    final ink = widget.color ?? (dark ? Colors.white : const Color(0xFF09090B));
    final surface = widget.backgroundColor ?? (dark ? const Color(0xFF141414) : Colors.white);
    final text = dark ? Colors.white : const Color(0xFF09090B);
    final data = _data;
    final selected = _selected != null && _selected! < data.length ? _selected : null;
    final metric = data.isEmpty
        ? 'No data'
        : (selected == null ? _number(data.last.value) : _number(data[selected].value));
    return SizedBox(
      width: widget.width,
      height: widget.height,
      child: Semantics(
        label: 'Arc Meter Gauge',
        value: selected == null ? '$metric ${widget.unit}' : _detail(data[selected]),
        child: DecoratedBox(
          decoration: BoxDecoration(
            color: surface,
            borderRadius: BorderRadius.circular(24),
            border: Border.all(color: text.withValues(alpha: 0.08)),
          ),
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                SizedBox(
                  height: 32,
                  child: Row(
                    children: [
                      Expanded(
                        child: FittedBox(
                          fit: BoxFit.scaleDown,
                          alignment: Alignment.centerLeft,
                          child: Row(
                            children: [
                              Text(
                                metric,
                                style: TextStyle(color: text, fontSize: 24, fontWeight: FontWeight.w700),
                              ),
                              const SizedBox(width: 6),
                              Text(
                                widget.unit,
                                style: TextStyle(color: text.withValues(alpha: 0.55), fontSize: 11),
                              ),
                            ],
                          ),
                        ),
                      ),
                      if (_sets.length > 1) ...[
                        const SizedBox(width: 10),
                        DropdownButtonHideUnderline(
                          child: DropdownButton<String>(
                            value: _active,
                            isDense: true,
                            borderRadius: BorderRadius.circular(12),
                            dropdownColor: surface,
                            style: TextStyle(color: text, fontSize: 11),
                            items: [
                              for (final key in _sets.keys) DropdownMenuItem(value: key, child: Text(key)),
                            ],
                            onChanged: (key) {
                              setState(() {
                                _dataset = key;
                                _selected = null;
                              });
                              widget.onSelected?.call(null);
                              _reveal();
                            },
                          ),
                        ),
                      ],
                    ],
                  ),
                ),
                const SizedBox(height: 10),
                Expanded(
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(14),
                    child: ColoredBox(
                      color: dark ? const Color(0xFF131313) : const Color(0xFFF4F4F6),
                      child: data.isEmpty
                          ? Center(
                              child: Text('No data', style: TextStyle(color: text.withValues(alpha: 0.5))),
                            )
                          : LayoutBuilder(
                              builder: (context, constraints) {
                                final size = constraints.biggest;
                                final hitPainter = _ChartPainter(
                                  data: data,
                                  ink: ink,
                                  text: text,
                                  selected: selected,
                                  progress: 1,
                                  mode: _active ?? 'Default',
                                );
                                return MouseRegion(
                                  onHover: (event) =>
                                      _select(hitPainter.hitIndex(event.localPosition, size), data),
                                  onExit: (_) => _select(null, data),
                                  child: GestureDetector(
                                    behavior: HitTestBehavior.opaque,
                                    onTapUp: (event) {
                                      final index = hitPainter.hitIndex(event.localPosition, size);
                                      _select(index == selected ? null : index, data);
                                    },
                                    child: Stack(
                                      fit: StackFit.expand,
                                      children: [
                                        AnimatedBuilder(
                                          animation: _animation,
                                          builder: (_, _) => CustomPaint(
                                            painter: _ChartPainter(
                                              data: data,
                                              ink: ink,
                                              text: text,
                                              selected: selected,
                                              mode: _active ?? 'Default',
                                              progress: Curves.easeOutCubic.transform(_animation.value),
                                            ),
                                          ),
                                        ),
                                        if (selected != null)
                                          Positioned(
                                            left: 8,
                                            right: 8,
                                            top: 6,
                                            child: IgnorePointer(
                                              child: DecoratedBox(
                                                decoration: BoxDecoration(
                                                  color: surface.withValues(alpha: 0.95),
                                                  borderRadius: BorderRadius.circular(8),
                                                ),
                                                child: Padding(
                                                  padding: const EdgeInsets.symmetric(
                                                    horizontal: 8,
                                                    vertical: 5,
                                                  ),
                                                  child: Text(
                                                    _detail(data[selected]),
                                                    maxLines: 2,
                                                    overflow: TextOverflow.ellipsis,
                                                    style: TextStyle(color: text, fontSize: 11),
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ),
                                      ],
                                    ),
                                  ),
                                );
                              },
                            ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

String _number(double value) {
  if (value.abs() >= 1000000) return '${(value / 1000000).toStringAsFixed(1)}M';
  if (value.abs() >= 1000) return '${(value / 1000).toStringAsFixed(1)}k';
  if (value == value.roundToDouble()) return value.toStringAsFixed(0);
  return value.toStringAsFixed(2).replaceFirst(RegExp(r'\.?0+$'), '');
}

class _ChartPainter extends CustomPainter {
  _ChartPainter({
    required this.data,
    required this.ink,
    required this.text,
    required this.selected,
    required this.progress,
    required this.mode,
  });
  final List<MonoRoundedMeterPoint> data;
  final Color ink;
  final Color text;
  final int? selected;
  final double progress;
  final String mode;

  Color tone(int i) => ink.withValues(alpha: selected == i ? 1 : (1 - i * 0.18).clamp(0.2, 1));
  Paint fill(Color color) => Paint()..color = color;
  Paint stroke(Color color, [double width = 2]) => Paint()
    ..color = color
    ..style = PaintingStyle.stroke
    ..strokeWidth = width
    ..strokeCap = StrokeCap.round
    ..strokeJoin = StrokeJoin.round;

  void label(
    Canvas canvas,
    String value,
    Offset at, {
    Color? color,
    double fontSize = 10,
    bool centered = false,
  }) {
    final painter = TextPainter(
      text: TextSpan(
        text: value,
        style: TextStyle(color: color ?? text.withValues(alpha: 0.5), fontSize: fontSize),
      ),
      textDirection: TextDirection.ltr,
      maxLines: 1,
      ellipsis: '…',
    )..layout(maxWidth: 110);
    painter.paint(canvas, centered ? at - Offset(painter.width / 2, 0) : at);
  }

  Offset center(Size size) => Offset(size.width / 2, size.height * 0.73);
  double radius(Size size) => math.min(size.width * 0.34, size.height * 0.56);

  int? hitIndex(Offset position, Size size) {
    if (data.isEmpty || !(Offset.zero & size).contains(position)) return null;

    final c = center(size), rr = radius(size), vector = position - c;
    return position.dy <= c.dy + 12 && vector.distance <= rr * 1.2 ? 0 : null;
  }

  @override
  void paint(Canvas canvas, Size size) {
    if (data.isEmpty || size.width < 40 || size.height < 40) return;
    canvas.save();
    canvas.clipRect(Offset.zero & size);

    final c = center(size), rr = radius(size), rect = Rect.fromCircle(center: c, radius: rr);
    canvas.drawArc(rect, math.pi, math.pi, false, stroke(ink.withValues(alpha: 0.08), rr * 0.2));
    final value = (data.first.value / 100).clamp(0, 1);
    canvas.drawArc(rect, math.pi, math.pi * value * progress, false, stroke(tone(0), rr * 0.2));
    label(
      canvas,
      '${_number(data.first.value)}%',
      c - const Offset(0, 28),
      color: text,
      centered: true,
      fontSize: 24,
    );
    label(canvas, '0', c + Offset(-rr, 13), centered: true);
    label(canvas, '100', c + Offset(rr, 13), centered: true);

    final angle = math.pi + math.pi * value * progress;
    final end = c + Offset(math.cos(angle), math.sin(angle)) * rr * 0.7;
    canvas.drawLine(c, end, stroke(ink, 3));
    canvas.drawCircle(c, 5, fill(ink));

    canvas.restore();
  }

  @override
  bool shouldRepaint(covariant _ChartPainter oldDelegate) =>
      !listEquals(data, oldDelegate.data) ||
      ink != oldDelegate.ink ||
      text != oldDelegate.text ||
      selected != oldDelegate.selected ||
      progress != oldDelegate.progress ||
      mode != oldDelegate.mode;
}
