// GENERATED by tool/gen_mono_charts.py. Edit the generator, then regenerate.
// MonoRoundedSankeyChart — Flow Sankey Channels.
// Inspired by Amicro (MIT, (c) 2026 Syed Subhan Uddin).
// Copy this file into your project. It depends only on Flutter and dart:math.
// Usage: MonoRoundedSankeyChart() or MonoRoundedSankeyChart(data: [MonoRoundedSankeyPoint(label: 'A', value: 42)])
import 'dart:math' as math;

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

/// One observation. Values use the units supplied to the chart.
@immutable
class MonoRoundedSankeyPoint {
  const MonoRoundedSankeyPoint({required this.label, required this.value});
  final String label;
  final double value;
}

/// A standalone, rounded chart with hover/tap inspection and an animated reveal.
/// Defaults are demonstration data; provide [data] or named [datasets] for your own.
/// Theme colours follow the surrounding Material theme. Reduced motion is respected.
class MonoRoundedSankeyChart extends StatefulWidget {
  const MonoRoundedSankeyChart({
    super.key,
    this.data,
    this.datasets,
    this.width = 420,
    this.height = 260,
    this.color,
    this.backgroundColor,
    this.unit = 'k tx/s',
    this.animate = true,
    this.duration = const Duration(milliseconds: 650),
    this.onSelected,
  }) : assert(width > 0),
       assert(height >= 140);

  /// A single series. Overrides the demonstration datasets when provided.
  final List<MonoRoundedSankeyPoint>? data;

  /// Named series shown in a selector. Takes precedence over [data].
  final Map<String, List<MonoRoundedSankeyPoint>>? datasets;
  final double width;
  final double height;
  final Color? color;
  final Color? backgroundColor;
  final String unit;
  final bool animate;
  final Duration duration;

  /// Reports the hovered/tapped observation; null when the selection is cleared.
  final ValueChanged<MonoRoundedSankeyPoint?>? onSelected;

  @override
  State<MonoRoundedSankeyChart> createState() => _ChartState();
}

const _demo = <String, List<MonoRoundedSankeyPoint>>{
  'Default': [
    MonoRoundedSankeyPoint(label: 'Mempool', value: 48.5),
    MonoRoundedSankeyPoint(label: 'RPC Direct', value: 35.7),
  ],
};

class _ChartState extends State<MonoRoundedSankeyChart> with SingleTickerProviderStateMixin {
  late final AnimationController _animation = AnimationController(vsync: this, duration: widget.duration);
  String? _dataset;
  int? _selected;
  bool? _reducedMotion;

  Map<String, List<MonoRoundedSankeyPoint>> get _sets =>
      widget.datasets ?? (widget.data == null ? _demo : const {});
  String? get _active => _sets.containsKey(_dataset) ? _dataset : (_sets.isEmpty ? null : _sets.keys.first);
  List<MonoRoundedSankeyPoint> get _data => List.unmodifiable(
    (_active == null ? widget.data ?? const <MonoRoundedSankeyPoint>[] : _sets[_active]!).where(
      (d) => d.value.isFinite,
    ),
  );

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final reduced = MediaQuery.disableAnimationsOf(context);
    if (_reducedMotion != reduced) {
      _reducedMotion = reduced;
      _reveal();
    }
  }

  @override
  void didUpdateWidget(covariant MonoRoundedSankeyChart oldWidget) {
    super.didUpdateWidget(oldWidget);
    _animation.duration = widget.duration;
    if (oldWidget.data != widget.data ||
        oldWidget.datasets != widget.datasets ||
        oldWidget.animate != widget.animate) {
      _selected = null;
      _reveal();
    }
  }

  void _reveal() {
    if (_reducedMotion == true || !widget.animate) {
      _animation.value = 1;
    } else {
      _animation.forward(from: 0);
    }
  }

  void _select(int? index, List<MonoRoundedSankeyPoint> data) {
    if (_selected == index) return;
    setState(() => _selected = index);
    widget.onSelected?.call(index == null ? null : data[index]);
  }

  @override
  void dispose() {
    _animation.dispose();
    super.dispose();
  }

  String _detail(MonoRoundedSankeyPoint d) => '${d.label}: ${_number(d.value)} ${widget.unit}';

  @override
  Widget build(BuildContext context) {
    final dark = Theme.of(context).brightness == Brightness.dark;
    final ink = widget.color ?? (dark ? Colors.white : const Color(0xFF09090B));
    final surface = widget.backgroundColor ?? (dark ? const Color(0xFF141414) : Colors.white);
    final text = dark ? Colors.white : const Color(0xFF09090B);
    final data = _data;
    final selected = _selected != null && _selected! < data.length ? _selected : null;
    final metric = data.isEmpty
        ? 'No data'
        : (selected == null
              ? _number(data.fold<double>(0, (sum, d) => sum + d.value))
              : _number(data[selected].value));
    return SizedBox(
      width: widget.width,
      height: widget.height,
      child: Semantics(
        label: 'Flow Sankey Channels',
        value: selected == null ? '$metric ${widget.unit}' : _detail(data[selected]),
        child: DecoratedBox(
          decoration: BoxDecoration(
            color: surface,
            borderRadius: BorderRadius.circular(24),
            border: Border.all(color: text.withValues(alpha: 0.08)),
          ),
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                SizedBox(
                  height: 32,
                  child: Row(
                    children: [
                      Expanded(
                        child: FittedBox(
                          fit: BoxFit.scaleDown,
                          alignment: Alignment.centerLeft,
                          child: Row(
                            children: [
                              Text(
                                metric,
                                style: TextStyle(color: text, fontSize: 24, fontWeight: FontWeight.w700),
                              ),
                              const SizedBox(width: 6),
                              Text(
                                widget.unit,
                                style: TextStyle(color: text.withValues(alpha: 0.55), fontSize: 11),
                              ),
                            ],
                          ),
                        ),
                      ),
                      if (_sets.length > 1) ...[
                        const SizedBox(width: 10),
                        DropdownButtonHideUnderline(
                          child: DropdownButton<String>(
                            value: _active,
                            isDense: true,
                            borderRadius: BorderRadius.circular(12),
                            dropdownColor: surface,
                            style: TextStyle(color: text, fontSize: 11),
                            items: [
                              for (final key in _sets.keys) DropdownMenuItem(value: key, child: Text(key)),
                            ],
                            onChanged: (key) {
                              setState(() {
                                _dataset = key;
                                _selected = null;
                              });
                              widget.onSelected?.call(null);
                              _reveal();
                            },
                          ),
                        ),
                      ],
                    ],
                  ),
                ),
                const SizedBox(height: 10),
                Expanded(
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(14),
                    child: ColoredBox(
                      color: dark ? const Color(0xFF131313) : const Color(0xFFF4F4F6),
                      child: data.isEmpty
                          ? Center(
                              child: Text('No data', style: TextStyle(color: text.withValues(alpha: 0.5))),
                            )
                          : LayoutBuilder(
                              builder: (context, constraints) {
                                final size = constraints.biggest;
                                final hitPainter = _ChartPainter(
                                  data: data,
                                  ink: ink,
                                  text: text,
                                  selected: selected,
                                  progress: 1,
                                  mode: _active ?? 'Default',
                                );
                                return MouseRegion(
                                  onHover: (event) =>
                                      _select(hitPainter.hitIndex(event.localPosition, size), data),
                                  onExit: (_) => _select(null, data),
                                  child: GestureDetector(
                                    behavior: HitTestBehavior.opaque,
                                    onTapUp: (event) {
                                      final index = hitPainter.hitIndex(event.localPosition, size);
                                      _select(index == selected ? null : index, data);
                                    },
                                    child: Stack(
                                      fit: StackFit.expand,
                                      children: [
                                        AnimatedBuilder(
                                          animation: _animation,
                                          builder: (_, _) => CustomPaint(
                                            painter: _ChartPainter(
                                              data: data,
                                              ink: ink,
                                              text: text,
                                              selected: selected,
                                              mode: _active ?? 'Default',
                                              progress: Curves.easeOutCubic.transform(_animation.value),
                                            ),
                                          ),
                                        ),
                                        if (selected != null)
                                          Positioned(
                                            left: 8,
                                            right: 8,
                                            top: 6,
                                            child: IgnorePointer(
                                              child: DecoratedBox(
                                                decoration: BoxDecoration(
                                                  color: surface.withValues(alpha: 0.95),
                                                  borderRadius: BorderRadius.circular(8),
                                                ),
                                                child: Padding(
                                                  padding: const EdgeInsets.symmetric(
                                                    horizontal: 8,
                                                    vertical: 5,
                                                  ),
                                                  child: Text(
                                                    _detail(data[selected]),
                                                    maxLines: 2,
                                                    overflow: TextOverflow.ellipsis,
                                                    style: TextStyle(color: text, fontSize: 11),
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ),
                                      ],
                                    ),
                                  ),
                                );
                              },
                            ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

String _number(double value) {
  if (value.abs() >= 1000000) return '${(value / 1000000).toStringAsFixed(1)}M';
  if (value.abs() >= 1000) return '${(value / 1000).toStringAsFixed(1)}k';
  if (value == value.roundToDouble()) return value.toStringAsFixed(0);
  return value.toStringAsFixed(2).replaceFirst(RegExp(r'\.?0+$'), '');
}

class _ChartPainter extends CustomPainter {
  _ChartPainter({
    required this.data,
    required this.ink,
    required this.text,
    required this.selected,
    required this.progress,
    required this.mode,
  });
  final List<MonoRoundedSankeyPoint> data;
  final Color ink;
  final Color text;
  final int? selected;
  final double progress;
  final String mode;

  Color tone(int i) => ink.withValues(alpha: selected == i ? 1 : (1 - i * 0.18).clamp(0.2, 1));
  Paint fill(Color color) => Paint()..color = color;
  Paint stroke(Color color, [double width = 2]) => Paint()
    ..color = color
    ..style = PaintingStyle.stroke
    ..strokeWidth = width
    ..strokeCap = StrokeCap.round
    ..strokeJoin = StrokeJoin.round;

  void label(
    Canvas canvas,
    String value,
    Offset at, {
    Color? color,
    double fontSize = 10,
    bool centered = false,
  }) {
    final painter = TextPainter(
      text: TextSpan(
        text: value,
        style: TextStyle(color: color ?? text.withValues(alpha: 0.5), fontSize: fontSize),
      ),
      textDirection: TextDirection.ltr,
      maxLines: 1,
      ellipsis: '…',
    )..layout(maxWidth: 110);
    painter.paint(canvas, centered ? at - Offset(painter.width / 2, 0) : at);
  }

  List<Rect> rows(Size size) {
    final h = (size.height - 24) / data.length;
    return [for (var i = 0; i < data.length; i++) Rect.fromLTWH(14, 12 + i * h, size.width - 28, h - 6)];
  }

  int? hitIndex(Offset position, Size size) {
    if (data.isEmpty || !(Offset.zero & size).contains(position)) return null;

    final boxes = rows(size);
    for (var i = 0; i < boxes.length; i++) {
      if (boxes[i].contains(position)) return i;
    }
    return null;
  }

  @override
  void paint(Canvas canvas, Size size) {
    if (data.isEmpty || size.width < 40 || size.height < 40) return;
    canvas.save();
    canvas.clipRect(Offset.zero & size);

    final boxes = rows(size);
    final sink = Rect.fromLTWH(size.width * 0.73, size.height * 0.34, size.width * 0.23, size.height * 0.32);
    final total = math.max(1.0, data.fold<double>(0, (sum, d) => sum + math.max(0, d.value)));
    for (var i = 0; i < data.length; i++) {
      final row = boxes[i];
      final source = Rect.fromLTWH(
        row.left,
        row.top + row.height * 0.15,
        size.width * 0.27,
        row.height * 0.7,
      );
      final path = Path()
        ..moveTo(source.right, source.center.dy)
        ..cubicTo(
          size.width * 0.46,
          source.center.dy,
          size.width * 0.55,
          sink.center.dy,
          sink.left,
          sink.center.dy,
        );
      final alpha = selected == null || selected == i ? 0.35 : 0.08;
      canvas.drawPath(
        path,
        stroke(
          ink.withValues(alpha: alpha),
          math.max(2.0, data[i].value / total * size.height * 0.24 * progress),
        ),
      );
      canvas.drawRRect(
        RRect.fromRectAndRadius(source, const Radius.circular(10)),
        fill(tone(i).withValues(alpha: 0.12)),
      );
      label(canvas, data[i].label, source.topLeft + const Offset(6, 6), color: text, fontSize: 9);
      label(canvas, '${_number(data[i].value)}k', source.topLeft + const Offset(6, 21), fontSize: 9);
    }
    canvas.drawRRect(RRect.fromRectAndRadius(sink, const Radius.circular(14)), fill(ink));
    final inverse = text == Colors.white ? Colors.black : Colors.white;
    label(
      canvas,
      'Leader Slot',
      Offset(sink.center.dx, sink.top + 10),
      centered: true,
      color: inverse,
      fontSize: 9,
    );
    label(
      canvas,
      '${_number(total)}k',
      Offset(sink.center.dx, sink.top + 27),
      centered: true,
      color: inverse,
      fontSize: 15,
    );

    canvas.restore();
  }

  @override
  bool shouldRepaint(covariant _ChartPainter oldDelegate) =>
      !listEquals(data, oldDelegate.data) ||
      ink != oldDelegate.ink ||
      text != oldDelegate.text ||
      selected != oldDelegate.selected ||
      progress != oldDelegate.progress ||
      mode != oldDelegate.mode;
}
