// GENERATED by tool/gen_mono_charts.py. Edit the generator, then regenerate.
// MonoRoundedScatterChart — Scatter Matrix.
// Inspired by Amicro (MIT, (c) 2026 Syed Subhan Uddin).
// Copy this file into your project. It depends only on Flutter and dart:math.
// Usage: MonoRoundedScatterChart() or MonoRoundedScatterChart(data: [MonoRoundedScatterPoint(label: 'A', value: 42)])
import 'dart:math' as math;

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

/// One observation. Values use the units supplied to the chart.
@immutable
class MonoRoundedScatterPoint {
  const MonoRoundedScatterPoint({required this.label, required this.value, this.x = 0, this.size = 100});
  final String label;
  final double value;
  final double x;
  final double size;
}

/// A standalone, rounded chart with hover/tap inspection and an animated reveal.
/// Defaults are demonstration data; provide [data] or named [datasets] for your own.
/// Theme colours follow the surrounding Material theme. Reduced motion is respected.
class MonoRoundedScatterChart extends StatefulWidget {
  const MonoRoundedScatterChart({
    super.key,
    this.data,
    this.datasets,
    this.width = 420,
    this.height = 260,
    this.color,
    this.backgroundColor,
    this.unit = 'stake',
    this.animate = true,
    this.duration = const Duration(milliseconds: 650),
    this.onSelected,
  }) : assert(width > 0),
       assert(height >= 140);

  /// A single series. Overrides the demonstration datasets when provided.
  final List<MonoRoundedScatterPoint>? data;

  /// Named series shown in a selector. Takes precedence over [data].
  final Map<String, List<MonoRoundedScatterPoint>>? datasets;
  final double width;
  final double height;
  final Color? color;
  final Color? backgroundColor;
  final String unit;
  final bool animate;
  final Duration duration;

  /// Reports the hovered/tapped observation; null when the selection is cleared.
  final ValueChanged<MonoRoundedScatterPoint?>? onSelected;

  @override
  State<MonoRoundedScatterChart> createState() => _ChartState();
}

const _demo = <String, List<MonoRoundedScatterPoint>>{
  'All': [
    MonoRoundedScatterPoint(label: 'Validator Alpha', value: 1450, x: 18, size: 280),
    MonoRoundedScatterPoint(label: 'Staking Prime', value: 890, x: 26, size: 220),
    MonoRoundedScatterPoint(label: 'SolNode 04', value: 640, x: 34, size: 180),
    MonoRoundedScatterPoint(label: 'Nexus Stake', value: 1120, x: 42, size: 260),
    MonoRoundedScatterPoint(label: 'Helios Node', value: 420, x: 55, size: 140),
    MonoRoundedScatterPoint(label: 'Apex Validator', value: 310, x: 68, size: 120),
    MonoRoundedScatterPoint(label: 'Atlas Core', value: 980, x: 22, size: 240),
  ],
  'Leaders': [
    MonoRoundedScatterPoint(label: 'Validator Alpha', value: 1450, x: 18, size: 280),
    MonoRoundedScatterPoint(label: 'Staking Prime', value: 890, x: 26, size: 220),
    MonoRoundedScatterPoint(label: 'Nexus Stake', value: 1120, x: 42, size: 260),
    MonoRoundedScatterPoint(label: 'Atlas Core', value: 980, x: 22, size: 240),
  ],
};

class _ChartState extends State<MonoRoundedScatterChart> with SingleTickerProviderStateMixin {
  late final AnimationController _animation = AnimationController(vsync: this, duration: widget.duration);
  String? _dataset;
  int? _selected;
  bool? _reducedMotion;

  Map<String, List<MonoRoundedScatterPoint>> get _sets =>
      widget.datasets ?? (widget.data == null ? _demo : const {});
  String? get _active => _sets.containsKey(_dataset) ? _dataset : (_sets.isEmpty ? null : _sets.keys.first);
  List<MonoRoundedScatterPoint> get _data => List.unmodifiable(
    (_active == null ? widget.data ?? const <MonoRoundedScatterPoint>[] : _sets[_active]!).where(
      (d) => d.value.isFinite && d.x.isFinite && d.size.isFinite,
    ),
  );

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final reduced = MediaQuery.disableAnimationsOf(context);
    if (_reducedMotion != reduced) {
      _reducedMotion = reduced;
      _reveal();
    }
  }

  @override
  void didUpdateWidget(covariant MonoRoundedScatterChart oldWidget) {
    super.didUpdateWidget(oldWidget);
    _animation.duration = widget.duration;
    if (oldWidget.data != widget.data ||
        oldWidget.datasets != widget.datasets ||
        oldWidget.animate != widget.animate) {
      _selected = null;
      _reveal();
    }
  }

  void _reveal() {
    if (_reducedMotion == true || !widget.animate) {
      _animation.value = 1;
    } else {
      _animation.forward(from: 0);
    }
  }

  void _select(int? index, List<MonoRoundedScatterPoint> data) {
    if (_selected == index) return;
    setState(() => _selected = index);
    widget.onSelected?.call(index == null ? null : data[index]);
  }

  @override
  void dispose() {
    _animation.dispose();
    super.dispose();
  }

  String _detail(MonoRoundedScatterPoint d) => '${d.label}: ${_number(d.x)} ms · ${_number(d.value)} stake';

  @override
  Widget build(BuildContext context) {
    final dark = Theme.of(context).brightness == Brightness.dark;
    final ink = widget.color ?? (dark ? Colors.white : const Color(0xFF09090B));
    final surface = widget.backgroundColor ?? (dark ? const Color(0xFF141414) : Colors.white);
    final text = dark ? Colors.white : const Color(0xFF09090B);
    final data = _data;
    final selected = _selected != null && _selected! < data.length ? _selected : null;
    final metric = data.isEmpty
        ? 'No data'
        : (selected == null ? _number(data.last.value) : _number(data[selected].value));
    return SizedBox(
      width: widget.width,
      height: widget.height,
      child: Semantics(
        label: 'Scatter Matrix',
        value: selected == null ? '$metric ${widget.unit}' : _detail(data[selected]),
        child: DecoratedBox(
          decoration: BoxDecoration(
            color: surface,
            borderRadius: BorderRadius.circular(24),
            border: Border.all(color: text.withValues(alpha: 0.08)),
          ),
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                SizedBox(
                  height: 32,
                  child: Row(
                    children: [
                      Expanded(
                        child: FittedBox(
                          fit: BoxFit.scaleDown,
                          alignment: Alignment.centerLeft,
                          child: Row(
                            children: [
                              Text(
                                metric,
                                style: TextStyle(color: text, fontSize: 24, fontWeight: FontWeight.w700),
                              ),
                              const SizedBox(width: 6),
                              Text(
                                widget.unit,
                                style: TextStyle(color: text.withValues(alpha: 0.55), fontSize: 11),
                              ),
                            ],
                          ),
                        ),
                      ),
                      if (_sets.length > 1) ...[
                        const SizedBox(width: 10),
                        DropdownButtonHideUnderline(
                          child: DropdownButton<String>(
                            value: _active,
                            isDense: true,
                            borderRadius: BorderRadius.circular(12),
                            dropdownColor: surface,
                            style: TextStyle(color: text, fontSize: 11),
                            items: [
                              for (final key in _sets.keys) DropdownMenuItem(value: key, child: Text(key)),
                            ],
                            onChanged: (key) {
                              setState(() {
                                _dataset = key;
                                _selected = null;
                              });
                              widget.onSelected?.call(null);
                              _reveal();
                            },
                          ),
                        ),
                      ],
                    ],
                  ),
                ),
                const SizedBox(height: 10),
                Expanded(
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(14),
                    child: ColoredBox(
                      color: dark ? const Color(0xFF131313) : const Color(0xFFF4F4F6),
                      child: data.isEmpty
                          ? Center(
                              child: Text('No data', style: TextStyle(color: text.withValues(alpha: 0.5))),
                            )
                          : LayoutBuilder(
                              builder: (context, constraints) {
                                final size = constraints.biggest;
                                final hitPainter = _ChartPainter(
                                  data: data,
                                  ink: ink,
                                  text: text,
                                  selected: selected,
                                  progress: 1,
                                  mode: _active ?? 'Default',
                                );
                                return MouseRegion(
                                  onHover: (event) =>
                                      _select(hitPainter.hitIndex(event.localPosition, size), data),
                                  onExit: (_) => _select(null, data),
                                  child: GestureDetector(
                                    behavior: HitTestBehavior.opaque,
                                    onTapUp: (event) {
                                      final index = hitPainter.hitIndex(event.localPosition, size);
                                      _select(index == selected ? null : index, data);
                                    },
                                    child: Stack(
                                      fit: StackFit.expand,
                                      children: [
                                        AnimatedBuilder(
                                          animation: _animation,
                                          builder: (_, _) => CustomPaint(
                                            painter: _ChartPainter(
                                              data: data,
                                              ink: ink,
                                              text: text,
                                              selected: selected,
                                              mode: _active ?? 'Default',
                                              progress: Curves.easeOutCubic.transform(_animation.value),
                                            ),
                                          ),
                                        ),
                                        if (selected != null)
                                          Positioned(
                                            left: 8,
                                            right: 8,
                                            top: 6,
                                            child: IgnorePointer(
                                              child: DecoratedBox(
                                                decoration: BoxDecoration(
                                                  color: surface.withValues(alpha: 0.95),
                                                  borderRadius: BorderRadius.circular(8),
                                                ),
                                                child: Padding(
                                                  padding: const EdgeInsets.symmetric(
                                                    horizontal: 8,
                                                    vertical: 5,
                                                  ),
                                                  child: Text(
                                                    _detail(data[selected]),
                                                    maxLines: 2,
                                                    overflow: TextOverflow.ellipsis,
                                                    style: TextStyle(color: text, fontSize: 11),
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ),
                                      ],
                                    ),
                                  ),
                                );
                              },
                            ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

String _number(double value) {
  if (value.abs() >= 1000000) return '${(value / 1000000).toStringAsFixed(1)}M';
  if (value.abs() >= 1000) return '${(value / 1000).toStringAsFixed(1)}k';
  if (value == value.roundToDouble()) return value.toStringAsFixed(0);
  return value.toStringAsFixed(2).replaceFirst(RegExp(r'\.?0+$'), '');
}

class _ChartPainter extends CustomPainter {
  _ChartPainter({
    required this.data,
    required this.ink,
    required this.text,
    required this.selected,
    required this.progress,
    required this.mode,
  });
  final List<MonoRoundedScatterPoint> data;
  final Color ink;
  final Color text;
  final int? selected;
  final double progress;
  final String mode;

  Color tone(int i) => ink.withValues(alpha: selected == i ? 1 : (1 - i * 0.18).clamp(0.2, 1));
  Paint fill(Color color) => Paint()..color = color;
  Paint stroke(Color color, [double width = 2]) => Paint()
    ..color = color
    ..style = PaintingStyle.stroke
    ..strokeWidth = width
    ..strokeCap = StrokeCap.round
    ..strokeJoin = StrokeJoin.round;

  void label(
    Canvas canvas,
    String value,
    Offset at, {
    Color? color,
    double fontSize = 10,
    bool centered = false,
  }) {
    final painter = TextPainter(
      text: TextSpan(
        text: value,
        style: TextStyle(color: color ?? text.withValues(alpha: 0.5), fontSize: fontSize),
      ),
      textDirection: TextDirection.ltr,
      maxLines: 1,
      ellipsis: '…',
    )..layout(maxWidth: 110);
    painter.paint(canvas, centered ? at - Offset(painter.width / 2, 0) : at);
  }

  Rect plot(Size size) =>
      Rect.fromLTRB(38, 14, math.max(39, size.width - 16), math.max(15, size.height - 26));
  (double, double) get domain {
    final values = <double>[
      for (final d in data) ...[d.value],
    ];
    final low = math.min(0.0, values.reduce(math.min));
    final high = values.reduce(math.max);
    final span = high - low;
    final pad = span.abs() < 0.000001 ? math.max(high.abs() * 0.1, 1.0) : span * 0.12;
    return (low == 0 ? 0.0 : low - pad, high + pad);
  }

  double y(double value, Rect r) {
    final (low, high) = domain;
    return r.bottom - (value - low) / (high - low) * r.height;
  }

  double x(int i, Rect r) => r.left + (i + 0.5) * r.width / data.length;
  void axes(Canvas canvas, Rect r) {
    final (low, high) = domain;
    for (var i = 0; i <= 3; i++) {
      final yy = r.top + r.height * i / 3;
      canvas.drawLine(Offset(r.left, yy), Offset(r.right, yy), stroke(text.withValues(alpha: 0.06), 1));
      label(canvas, _number(high - (high - low) * i / 3), Offset(3, yy - 5), fontSize: 9);
    }
  }

  double get minX => math.min(0.0, data.map((d) => d.x).reduce(math.min));
  double get maxX => math.max(minX + 1, data.map((d) => d.x).reduce(math.max) * 1.12);
  List<Offset> anchors(Size size) {
    final r = plot(size);
    return [for (final d in data) Offset(r.left + (d.x - minX) / (maxX - minX) * r.width, y(d.value, r))];
  }

  int? hitIndex(Offset position, Size size) {
    if (data.isEmpty || !(Offset.zero & size).contains(position)) return null;

    final positions = anchors(size);
    var best = 0;
    var distance = double.infinity;
    for (var i = 0; i < positions.length; i++) {
      final candidate = (positions[i] - position).distance;
      if (candidate < distance) {
        best = i;
        distance = candidate;
      }
    }
    return distance <= 28 ? best : null;
  }

  @override
  void paint(Canvas canvas, Size size) {
    if (data.isEmpty || size.width < 40 || size.height < 40) return;
    canvas.save();
    canvas.clipRect(Offset.zero & size);

    final r = plot(size);
    axes(canvas, r);
    final points = anchors(size);
    final maxSize = math.max(1.0, data.map((d) => d.size.abs()).reduce(math.max));
    for (var i = 0; i < data.length; i++) {
      final radius = (5 + math.sqrt(math.max(0, data[i].size) / maxSize) * 5) * progress;
      canvas.drawCircle(points[i], radius, fill(tone(i).withValues(alpha: selected == i ? 0.8 : 0.28)));
      canvas.drawCircle(points[i], radius, stroke(tone(i), selected == i ? 2.5 : 1.5));
    }
    label(canvas, _number(minX), Offset(r.left, r.bottom + 7), fontSize: 9);
    label(canvas, _number(maxX), Offset(r.right - 22, r.bottom + 7), fontSize: 9);

    canvas.restore();
  }

  @override
  bool shouldRepaint(covariant _ChartPainter oldDelegate) =>
      !listEquals(data, oldDelegate.data) ||
      ink != oldDelegate.ink ||
      text != oldDelegate.text ||
      selected != oldDelegate.selected ||
      progress != oldDelegate.progress ||
      mode != oldDelegate.mode;
}
