// GENERATED by tool/gen_mono_charts.py. Edit the generator, then regenerate.
// MonoActivityHeatmap — Activity Heatmap.
// Inspired by Amicro (MIT, (c) 2026 Syed Subhan Uddin).
// Copy this file into your project. It depends only on Flutter and dart:math.
// Usage: MonoActivityHeatmap() or MonoActivityHeatmap(data: [MonoActivityHeatmapPoint(label: 'A', value: 42)])
import 'dart:math' as math;

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

/// One observation. Values use the units supplied to the chart.
@immutable
class MonoActivityHeatmapPoint {
  const MonoActivityHeatmapPoint({required this.label, required this.value});
  final String label;
  final double value;
}

/// A standalone, rounded chart with hover/tap inspection and an animated reveal.
/// Defaults are demonstration data; provide [data] or named [datasets] for your own.
/// Theme colours follow the surrounding Material theme. Reduced motion is respected.
class MonoActivityHeatmap extends StatefulWidget {
  const MonoActivityHeatmap({
    super.key,
    this.data,
    this.datasets,
    this.width = 420,
    this.height = 260,
    this.color,
    this.backgroundColor,
    this.unit = 'commits',
    this.animate = true,
    this.duration = const Duration(milliseconds: 650),
    this.onSelected,
  }) : assert(width > 0),
       assert(height >= 140);

  /// A single series. Overrides the demonstration datasets when provided.
  final List<MonoActivityHeatmapPoint>? data;

  /// Named series shown in a selector. Takes precedence over [data].
  final Map<String, List<MonoActivityHeatmapPoint>>? datasets;
  final double width;
  final double height;
  final Color? color;
  final Color? backgroundColor;
  final String unit;
  final bool animate;
  final Duration duration;

  /// Reports the hovered/tapped observation; null when the selection is cleared.
  final ValueChanged<MonoActivityHeatmapPoint?>? onSelected;

  @override
  State<MonoActivityHeatmap> createState() => _ChartState();
}

const _demo = <String, List<MonoActivityHeatmapPoint>>{
  'Default': [
    MonoActivityHeatmapPoint(label: 'Week 1, day 1', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 1, day 2', value: 3),
    MonoActivityHeatmapPoint(label: 'Week 1, day 3', value: 16),
    MonoActivityHeatmapPoint(label: 'Week 1, day 4', value: 13),
    MonoActivityHeatmapPoint(label: 'Week 1, day 5', value: 10),
    MonoActivityHeatmapPoint(label: 'Week 1, day 6', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 1, day 7', value: 4),
    MonoActivityHeatmapPoint(label: 'Week 2, day 1', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 2, day 2', value: 14),
    MonoActivityHeatmapPoint(label: 'Week 2, day 3', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 2, day 4', value: 8),
    MonoActivityHeatmapPoint(label: 'Week 2, day 5', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 2, day 6', value: 2),
    MonoActivityHeatmapPoint(label: 'Week 2, day 7', value: 15),
    MonoActivityHeatmapPoint(label: 'Week 3, day 1', value: 12),
    MonoActivityHeatmapPoint(label: 'Week 3, day 2', value: 9),
    MonoActivityHeatmapPoint(label: 'Week 3, day 3', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 3, day 4', value: 3),
    MonoActivityHeatmapPoint(label: 'Week 3, day 5', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 3, day 6', value: 13),
    MonoActivityHeatmapPoint(label: 'Week 3, day 7', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 4, day 1', value: 7),
    MonoActivityHeatmapPoint(label: 'Week 4, day 2', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 4, day 3', value: 1),
    MonoActivityHeatmapPoint(label: 'Week 4, day 4', value: 14),
    MonoActivityHeatmapPoint(label: 'Week 4, day 5', value: 11),
    MonoActivityHeatmapPoint(label: 'Week 4, day 6', value: 8),
    MonoActivityHeatmapPoint(label: 'Week 4, day 7', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 5, day 1', value: 2),
    MonoActivityHeatmapPoint(label: 'Week 5, day 2', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 5, day 3', value: 12),
    MonoActivityHeatmapPoint(label: 'Week 5, day 4', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 5, day 5', value: 6),
    MonoActivityHeatmapPoint(label: 'Week 5, day 6', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 5, day 7', value: 16),
    MonoActivityHeatmapPoint(label: 'Week 6, day 1', value: 13),
    MonoActivityHeatmapPoint(label: 'Week 6, day 2', value: 10),
    MonoActivityHeatmapPoint(label: 'Week 6, day 3', value: 7),
    MonoActivityHeatmapPoint(label: 'Week 6, day 4', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 6, day 5', value: 1),
    MonoActivityHeatmapPoint(label: 'Week 6, day 6', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 6, day 7', value: 11),
    MonoActivityHeatmapPoint(label: 'Week 7, day 1', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 7, day 2', value: 5),
    MonoActivityHeatmapPoint(label: 'Week 7, day 3', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 7, day 4', value: 15),
    MonoActivityHeatmapPoint(label: 'Week 7, day 5', value: 12),
    MonoActivityHeatmapPoint(label: 'Week 7, day 6', value: 9),
    MonoActivityHeatmapPoint(label: 'Week 7, day 7', value: 6),
    MonoActivityHeatmapPoint(label: 'Week 8, day 1', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 8, day 2', value: 16),
    MonoActivityHeatmapPoint(label: 'Week 8, day 3', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 8, day 4', value: 10),
    MonoActivityHeatmapPoint(label: 'Week 8, day 5', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 8, day 6', value: 4),
    MonoActivityHeatmapPoint(label: 'Week 8, day 7', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 9, day 1', value: 14),
    MonoActivityHeatmapPoint(label: 'Week 9, day 2', value: 11),
    MonoActivityHeatmapPoint(label: 'Week 9, day 3', value: 8),
    MonoActivityHeatmapPoint(label: 'Week 9, day 4', value: 5),
    MonoActivityHeatmapPoint(label: 'Week 9, day 5', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 9, day 6', value: 15),
    MonoActivityHeatmapPoint(label: 'Week 9, day 7', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 10, day 1', value: 9),
    MonoActivityHeatmapPoint(label: 'Week 10, day 2', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 10, day 3', value: 3),
    MonoActivityHeatmapPoint(label: 'Week 10, day 4', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 10, day 5', value: 13),
    MonoActivityHeatmapPoint(label: 'Week 10, day 6', value: 10),
    MonoActivityHeatmapPoint(label: 'Week 10, day 7', value: 7),
    MonoActivityHeatmapPoint(label: 'Week 11, day 1', value: 4),
    MonoActivityHeatmapPoint(label: 'Week 11, day 2', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 11, day 3', value: 14),
    MonoActivityHeatmapPoint(label: 'Week 11, day 4', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 11, day 5', value: 8),
    MonoActivityHeatmapPoint(label: 'Week 11, day 6', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 11, day 7', value: 2),
    MonoActivityHeatmapPoint(label: 'Week 12, day 1', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 12, day 2', value: 12),
    MonoActivityHeatmapPoint(label: 'Week 12, day 3', value: 9),
    MonoActivityHeatmapPoint(label: 'Week 12, day 4', value: 6),
    MonoActivityHeatmapPoint(label: 'Week 12, day 5', value: 3),
    MonoActivityHeatmapPoint(label: 'Week 12, day 6', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 12, day 7', value: 13),
    MonoActivityHeatmapPoint(label: 'Week 13, day 1', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 13, day 2', value: 7),
    MonoActivityHeatmapPoint(label: 'Week 13, day 3', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 13, day 4', value: 1),
    MonoActivityHeatmapPoint(label: 'Week 13, day 5', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 13, day 6', value: 11),
    MonoActivityHeatmapPoint(label: 'Week 13, day 7', value: 8),
    MonoActivityHeatmapPoint(label: 'Week 14, day 1', value: 5),
    MonoActivityHeatmapPoint(label: 'Week 14, day 2', value: 2),
    MonoActivityHeatmapPoint(label: 'Week 14, day 3', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 14, day 4', value: 12),
    MonoActivityHeatmapPoint(label: 'Week 14, day 5', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 14, day 6', value: 6),
    MonoActivityHeatmapPoint(label: 'Week 14, day 7', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 15, day 1', value: 16),
    MonoActivityHeatmapPoint(label: 'Week 15, day 2', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 15, day 3', value: 10),
    MonoActivityHeatmapPoint(label: 'Week 15, day 4', value: 7),
    MonoActivityHeatmapPoint(label: 'Week 15, day 5', value: 4),
    MonoActivityHeatmapPoint(label: 'Week 15, day 6', value: 1),
    MonoActivityHeatmapPoint(label: 'Week 15, day 7', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 16, day 1', value: 11),
    MonoActivityHeatmapPoint(label: 'Week 16, day 2', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 16, day 3', value: 5),
    MonoActivityHeatmapPoint(label: 'Week 16, day 4', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 16, day 5', value: 15),
    MonoActivityHeatmapPoint(label: 'Week 16, day 6', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 16, day 7', value: 9),
    MonoActivityHeatmapPoint(label: 'Week 17, day 1', value: 6),
    MonoActivityHeatmapPoint(label: 'Week 17, day 2', value: 3),
    MonoActivityHeatmapPoint(label: 'Week 17, day 3', value: 16),
    MonoActivityHeatmapPoint(label: 'Week 17, day 4', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 17, day 5', value: 10),
    MonoActivityHeatmapPoint(label: 'Week 17, day 6', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 17, day 7', value: 4),
    MonoActivityHeatmapPoint(label: 'Week 18, day 1', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 18, day 2', value: 14),
    MonoActivityHeatmapPoint(label: 'Week 18, day 3', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 18, day 4', value: 8),
    MonoActivityHeatmapPoint(label: 'Week 18, day 5', value: 5),
    MonoActivityHeatmapPoint(label: 'Week 18, day 6', value: 2),
    MonoActivityHeatmapPoint(label: 'Week 18, day 7', value: 15),
    MonoActivityHeatmapPoint(label: 'Week 19, day 1', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 19, day 2', value: 9),
    MonoActivityHeatmapPoint(label: 'Week 19, day 3', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 19, day 4', value: 3),
    MonoActivityHeatmapPoint(label: 'Week 19, day 5', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 19, day 6', value: 13),
    MonoActivityHeatmapPoint(label: 'Week 19, day 7', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 20, day 1', value: 7),
    MonoActivityHeatmapPoint(label: 'Week 20, day 2', value: 4),
    MonoActivityHeatmapPoint(label: 'Week 20, day 3', value: 1),
    MonoActivityHeatmapPoint(label: 'Week 20, day 4', value: 14),
    MonoActivityHeatmapPoint(label: 'Week 20, day 5', value: 0),
    MonoActivityHeatmapPoint(label: 'Week 20, day 6', value: 8),
    MonoActivityHeatmapPoint(label: 'Week 20, day 7', value: 0),
  ],
};

class _ChartState extends State<MonoActivityHeatmap> with SingleTickerProviderStateMixin {
  late final AnimationController _animation = AnimationController(vsync: this, duration: widget.duration);
  String? _dataset;
  int? _selected;
  bool? _reducedMotion;

  Map<String, List<MonoActivityHeatmapPoint>> get _sets =>
      widget.datasets ?? (widget.data == null ? _demo : const {});
  String? get _active => _sets.containsKey(_dataset) ? _dataset : (_sets.isEmpty ? null : _sets.keys.first);
  List<MonoActivityHeatmapPoint> get _data => List.unmodifiable(
    (_active == null ? widget.data ?? const <MonoActivityHeatmapPoint>[] : _sets[_active]!).where(
      (d) => d.value.isFinite,
    ),
  );

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final reduced = MediaQuery.disableAnimationsOf(context);
    if (_reducedMotion != reduced) {
      _reducedMotion = reduced;
      _reveal();
    }
  }

  @override
  void didUpdateWidget(covariant MonoActivityHeatmap oldWidget) {
    super.didUpdateWidget(oldWidget);
    _animation.duration = widget.duration;
    if (oldWidget.data != widget.data ||
        oldWidget.datasets != widget.datasets ||
        oldWidget.animate != widget.animate) {
      _selected = null;
      _reveal();
    }
  }

  void _reveal() {
    if (_reducedMotion == true || !widget.animate) {
      _animation.value = 1;
    } else {
      _animation.forward(from: 0);
    }
  }

  void _select(int? index, List<MonoActivityHeatmapPoint> data) {
    if (_selected == index) return;
    setState(() => _selected = index);
    widget.onSelected?.call(index == null ? null : data[index]);
  }

  @override
  void dispose() {
    _animation.dispose();
    super.dispose();
  }

  String _detail(MonoActivityHeatmapPoint d) => '${d.label}: ${_number(d.value)} ${widget.unit}';

  @override
  Widget build(BuildContext context) {
    final dark = Theme.of(context).brightness == Brightness.dark;
    final ink = widget.color ?? const Color(0xFF39D353);
    final surface = widget.backgroundColor ?? (dark ? const Color(0xFF141414) : Colors.white);
    final text = dark ? Colors.white : const Color(0xFF09090B);
    final data = _data;
    final selected = _selected != null && _selected! < data.length ? _selected : null;
    final metric = data.isEmpty
        ? 'No data'
        : (selected == null
              ? _number(data.fold<double>(0, (sum, d) => sum + d.value))
              : _number(data[selected].value));
    return SizedBox(
      width: widget.width,
      height: widget.height,
      child: Semantics(
        label: 'Activity Heatmap',
        value: selected == null ? '$metric ${widget.unit}' : _detail(data[selected]),
        child: DecoratedBox(
          decoration: BoxDecoration(
            color: surface,
            borderRadius: BorderRadius.circular(24),
            border: Border.all(color: text.withValues(alpha: 0.08)),
          ),
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                SizedBox(
                  height: 32,
                  child: Row(
                    children: [
                      Expanded(
                        child: FittedBox(
                          fit: BoxFit.scaleDown,
                          alignment: Alignment.centerLeft,
                          child: Row(
                            children: [
                              Text(
                                metric,
                                style: TextStyle(color: text, fontSize: 24, fontWeight: FontWeight.w700),
                              ),
                              const SizedBox(width: 6),
                              Text(
                                widget.unit,
                                style: TextStyle(color: text.withValues(alpha: 0.55), fontSize: 11),
                              ),
                            ],
                          ),
                        ),
                      ),
                      if (_sets.length > 1) ...[
                        const SizedBox(width: 10),
                        DropdownButtonHideUnderline(
                          child: DropdownButton<String>(
                            value: _active,
                            isDense: true,
                            borderRadius: BorderRadius.circular(12),
                            dropdownColor: surface,
                            style: TextStyle(color: text, fontSize: 11),
                            items: [
                              for (final key in _sets.keys) DropdownMenuItem(value: key, child: Text(key)),
                            ],
                            onChanged: (key) {
                              setState(() {
                                _dataset = key;
                                _selected = null;
                              });
                              widget.onSelected?.call(null);
                              _reveal();
                            },
                          ),
                        ),
                      ],
                    ],
                  ),
                ),
                const SizedBox(height: 10),
                Expanded(
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(14),
                    child: ColoredBox(
                      color: dark ? const Color(0xFF131313) : const Color(0xFFF4F4F6),
                      child: data.isEmpty
                          ? Center(
                              child: Text('No data', style: TextStyle(color: text.withValues(alpha: 0.5))),
                            )
                          : LayoutBuilder(
                              builder: (context, constraints) {
                                final size = constraints.biggest;
                                final hitPainter = _ChartPainter(
                                  data: data,
                                  ink: ink,
                                  text: text,
                                  selected: selected,
                                  progress: 1,
                                  mode: _active ?? 'Default',
                                );
                                return MouseRegion(
                                  onHover: (event) =>
                                      _select(hitPainter.hitIndex(event.localPosition, size), data),
                                  onExit: (_) => _select(null, data),
                                  child: GestureDetector(
                                    behavior: HitTestBehavior.opaque,
                                    onTapUp: (event) {
                                      final index = hitPainter.hitIndex(event.localPosition, size);
                                      _select(index == selected ? null : index, data);
                                    },
                                    child: Stack(
                                      fit: StackFit.expand,
                                      children: [
                                        AnimatedBuilder(
                                          animation: _animation,
                                          builder: (_, _) => CustomPaint(
                                            painter: _ChartPainter(
                                              data: data,
                                              ink: ink,
                                              text: text,
                                              selected: selected,
                                              mode: _active ?? 'Default',
                                              progress: Curves.easeOutCubic.transform(_animation.value),
                                            ),
                                          ),
                                        ),
                                        if (selected != null)
                                          Positioned(
                                            left: 8,
                                            right: 8,
                                            top: 6,
                                            child: IgnorePointer(
                                              child: DecoratedBox(
                                                decoration: BoxDecoration(
                                                  color: surface.withValues(alpha: 0.95),
                                                  borderRadius: BorderRadius.circular(8),
                                                ),
                                                child: Padding(
                                                  padding: const EdgeInsets.symmetric(
                                                    horizontal: 8,
                                                    vertical: 5,
                                                  ),
                                                  child: Text(
                                                    _detail(data[selected]),
                                                    maxLines: 2,
                                                    overflow: TextOverflow.ellipsis,
                                                    style: TextStyle(color: text, fontSize: 11),
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ),
                                      ],
                                    ),
                                  ),
                                );
                              },
                            ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

String _number(double value) {
  if (value.abs() >= 1000000) return '${(value / 1000000).toStringAsFixed(1)}M';
  if (value.abs() >= 1000) return '${(value / 1000).toStringAsFixed(1)}k';
  if (value == value.roundToDouble()) return value.toStringAsFixed(0);
  return value.toStringAsFixed(2).replaceFirst(RegExp(r'\.?0+$'), '');
}

class _ChartPainter extends CustomPainter {
  _ChartPainter({
    required this.data,
    required this.ink,
    required this.text,
    required this.selected,
    required this.progress,
    required this.mode,
  });
  final List<MonoActivityHeatmapPoint> data;
  final Color ink;
  final Color text;
  final int? selected;
  final double progress;
  final String mode;

  Color tone(int i) => ink.withValues(alpha: selected == i ? 1 : (1 - i * 0.18).clamp(0.2, 1));
  Paint fill(Color color) => Paint()..color = color;
  Paint stroke(Color color, [double width = 2]) => Paint()
    ..color = color
    ..style = PaintingStyle.stroke
    ..strokeWidth = width
    ..strokeCap = StrokeCap.round
    ..strokeJoin = StrokeJoin.round;

  void label(
    Canvas canvas,
    String value,
    Offset at, {
    Color? color,
    double fontSize = 10,
    bool centered = false,
  }) {
    final painter = TextPainter(
      text: TextSpan(
        text: value,
        style: TextStyle(color: color ?? text.withValues(alpha: 0.5), fontSize: fontSize),
      ),
      textDirection: TextDirection.ltr,
      maxLines: 1,
      ellipsis: '…',
    )..layout(maxWidth: 110);
    painter.paint(canvas, centered ? at - Offset(painter.width / 2, 0) : at);
  }

  List<Rect> cells(Size size) {
    const rows = 7;
    final cols = (data.length / rows).ceil();
    final r = Rect.fromLTRB(30, 24, size.width - 12, size.height - 24);
    final width = r.width / cols, height = r.height / rows;
    return [
      for (var i = 0; i < data.length; i++)
        Rect.fromLTWH(
          r.left + (i ~/ rows) * width + 2,
          r.top + (i % rows) * height + 2,
          math.max(0, width - 4),
          math.max(0, height - 4),
        ),
    ];
  }

  int? hitIndex(Offset position, Size size) {
    if (data.isEmpty || !(Offset.zero & size).contains(position)) return null;

    final boxes = cells(size);
    for (var i = 0; i < boxes.length; i++) {
      if (boxes[i].contains(position)) return i;
    }
    return null;
  }

  @override
  void paint(Canvas canvas, Size size) {
    if (data.isEmpty || size.width < 40 || size.height < 40) return;
    canvas.save();
    canvas.clipRect(Offset.zero & size);

    final boxes = cells(size);
    final maxValue = math.max(1.0, data.map((d) => d.value).reduce(math.max));
    for (var i = 0; i < boxes.length; i++) {
      final opacity = (0.06 + math.max(0, data[i].value) / maxValue * 0.94) * progress;
      final rr = RRect.fromRectAndRadius(boxes[i], const Radius.circular(3));
      canvas.drawRRect(rr, fill(tone(0).withValues(alpha: opacity.clamp(0, 1))));
      if (selected == i) canvas.drawRRect(rr, stroke(text, 1.5));
    }

    const days = ['M', 'T', 'W', 'T', 'F', 'S', 'S'];
    for (var i = 0; i < math.min(7, boxes.length); i++) {
      label(canvas, days[i], Offset(9, boxes[i].center.dy - 5), fontSize: 9);
    }
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May'];
    for (var i = 0; i < 5; i++) {
      label(canvas, months[i], Offset(30 + i * (size.width - 42) / 5, 6), fontSize: 9);
    }
    label(canvas, 'Less', Offset(30, size.height - 16), fontSize: 9);
    for (var i = 0; i < 5; i++) {
      canvas.drawRRect(
        RRect.fromRectAndRadius(
          Rect.fromLTWH(size.width - 100 + i * 12, size.height - 16, 9, 9),
          const Radius.circular(2),
        ),
        fill(ink.withValues(alpha: 0.08 + i * 0.23)),
      );
    }
    label(canvas, 'More', Offset(size.width - 36, size.height - 17), fontSize: 9);

    canvas.restore();
  }

  @override
  bool shouldRepaint(covariant _ChartPainter oldDelegate) =>
      !listEquals(data, oldDelegate.data) ||
      ink != oldDelegate.ink ||
      text != oldDelegate.text ||
      selected != oldDelegate.selected ||
      progress != oldDelegate.progress ||
      mode != oldDelegate.mode;
}
